### ISSUE TITLE
WebODM polygon clipping tool not working

### ISSUE THREAD

**Issue by picameratk** [OpenDroneMap/WebODM#1301]
****************************************
### How did you install WebODM (docker, installer, etc.)?

Docker on Window 11

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Windows 11 and Microsoft Edge or Firefox

### What is the problem?

When viewing in 3D I attempt to use the polygon 3D tool, by placing points on my map, and the inside and outside buttons do nothing.  Note that the volume clip works.  I ran a ./webodm.sh update and tried again as well. 

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

[Type answer here]

**Comment by picameratk** [comment]
I have created a video of the problem.  https://youtu.be/kja8zFQFdJE

**Comment by pierotofy** [comment]
Thanks for the report and video @picameratk :pray: this should be fixed with #1436

**Comment by picameratk** [comment]
I send you this via email because github was not sending me a verification code but...

The fix for Potree #1436 will be reflected in webodm or docker desktop?  I have update both to the latest levels and still have the problem so I may  have expected the fix to be embedded too soon.
